/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as BuildingsRouteImport } from './routes/buildings'
import { Route as ClassroomsRouteImport } from './routes/classrooms'
import { Route as DepartmentsRouteImport } from './routes/departments'
import { Route as EventsRouteImport } from './routes/events'
import { Route as LabsRouteImport } from './routes/labs'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NavigationRouteImport } from './routes/navigation'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as AdminAttendanceRouteImport } from './routes/admin/attendance'
import { Route as AdminBuildingsRouteImport } from './routes/admin/buildings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildingsRoute = BuildingsRouteImport.update({
  id: '/buildings',
  path: '/buildings',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassroomsRoute = ClassroomsRouteImport.update({
  id: '/classrooms',
  path: '/classrooms',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsRoute = DepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const LabsRoute = LabsRouteImport.update({
  id: '/labs',
  path: '/labs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NavigationRoute = NavigationRouteImport.update({
  id: '/navigation',
  path: '/navigation',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAttendanceRoute = AdminAttendanceRouteImport.update({
  id: '/admin/attendance',
  path: '/admin/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBuildingsRoute = AdminBuildingsRouteImport.update({
  id: '/admin/buildings',
  path: '/admin/buildings',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/buildings': typeof BuildingsRoute
  '/classrooms': typeof ClassroomsRoute
  '/departments': typeof DepartmentsRoute
  '/events': typeof EventsRoute
  '/labs': typeof LabsRoute
  '/login': typeof LoginRoute
  '/navigation': typeof NavigationRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/buildings': typeof AdminBuildingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/buildings': typeof BuildingsRoute
  '/classrooms': typeof ClassroomsRoute
  '/departments': typeof DepartmentsRoute
  '/events': typeof EventsRoute
  '/labs': typeof LabsRoute
  '/login': typeof LoginRoute
  '/navigation': typeof NavigationRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/buildings': typeof AdminBuildingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/buildings': typeof BuildingsRoute
  '/classrooms': typeof ClassroomsRoute
  '/departments': typeof DepartmentsRoute
  '/events': typeof EventsRoute
  '/labs': typeof LabsRoute
  '/login': typeof LoginRoute
  '/navigation': typeof NavigationRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/buildings': typeof AdminBuildingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/buildings'
    | '/classrooms'
    | '/departments'
    | '/events'
    | '/labs'
    | '/login'
    | '/navigation'
    | '/register'
    | '/search'
    | '/settings'
    | '/admin/attendance'
    | '/admin/buildings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/buildings'
    | '/classrooms'
    | '/departments'
    | '/events'
    | '/labs'
    | '/login'
    | '/navigation'
    | '/register'
    | '/search'
    | '/settings'
    | '/admin/attendance'
    | '/admin/buildings'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/buildings'
    | '/classrooms'
    | '/departments'
    | '/events'
    | '/labs'
    | '/login'
    | '/navigation'
    | '/register'
    | '/search'
    | '/settings'
    | '/admin/attendance'
    | '/admin/buildings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  BuildingsRoute: typeof BuildingsRoute
  ClassroomsRoute: typeof ClassroomsRoute
  DepartmentsRoute: typeof DepartmentsRoute
  EventsRoute: typeof EventsRoute
  LabsRoute: typeof LabsRoute
  LoginRoute: typeof LoginRoute
  NavigationRoute: typeof NavigationRoute
  RegisterRoute: typeof RegisterRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  AdminAttendanceRoute: typeof AdminAttendanceRoute
  AdminBuildingsRoute: typeof AdminBuildingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buildings': {
      id: '/buildings'
      path: '/buildings'
      fullPath: '/buildings'
      preLoaderRoute: typeof BuildingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classrooms': {
      id: '/classrooms'
      path: '/classrooms'
      fullPath: '/classrooms'
      preLoaderRoute: typeof ClassroomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments': {
      id: '/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof DepartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labs': {
      id: '/labs'
      path: '/labs'
      fullPath: '/labs'
      preLoaderRoute: typeof LabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/navigation': {
      id: '/navigation'
      path: '/navigation'
      fullPath: '/navigation'
      preLoaderRoute: typeof NavigationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/attendance': {
      id: '/admin/attendance'
      path: '/admin/attendance'
      fullPath: '/admin/attendance'
      preLoaderRoute: typeof AdminAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/buildings': {
      id: '/admin/buildings'
      path: '/admin/buildings'
      fullPath: '/admin/buildings'
      preLoaderRoute: typeof AdminBuildingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  BuildingsRoute: BuildingsRoute,
  ClassroomsRoute: ClassroomsRoute,
  DepartmentsRoute: DepartmentsRoute,
  EventsRoute: EventsRoute,
  LabsRoute: LabsRoute,
  LoginRoute: LoginRoute,
  NavigationRoute: NavigationRoute,
  RegisterRoute: RegisterRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  AdminAttendanceRoute: AdminAttendanceRoute,
  AdminBuildingsRoute: AdminBuildingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
